### ISSUE TITLE
Build error when importing graphql_flutter.dart

### ISSUE THREAD

**Issue by leonvisscher** [zino-hofmann/graphql-flutter#1213]
**Describe the issue**
When importing the plugin into my flutter main file, building the project throws the following error:

```
: Error: 'cthrow' isn't a type.
../…/src/link.dart:172
      cthrow ServerException(
      ^^^^^^
: Error: Expected ';' after this.
../…/src/link.dart:172
      cthrow ServerException(
             ^^^^^^^^^^^^^^^
: Error: Expected ')' before this.
../…/src/link.dart:173
        originalException: e,
                         ^
: Error: The getter 'originalException' isn't defined for the class 'HttpLink'.
../…/src/link.dart:173
- 'HttpLink' is from 'package:gql_http_link/src/link.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/gql_http_link-0.4.2/lib/src/link.dart').
../…/src/link.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'originalException'.
        originalException: e,
        ^^^^^^^^^^^^^^^^^

: Error: A non-null value must be returned since the return type 'Response' doesn't allow null.
../…/src/link.dart:166
- 'Response' is from 'package:http/src/response.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.5/lib/src/response.dart').
package:http/src/response.dart:1
  Future<http.Response> _executeRequest(Request request) async {

Failed to package /Users/user/projects/hello_world.
    Command PhaseScriptExecution failed with a nonzero exit code
```

**To Reproduce (MUST BE PROVIDED)**

1. When adding the line `import 'package:graphql_flutter/graphql_flutter.dart';` at the top of my simple main.dart file this error is thrown:
```
import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bird App',
      home: Container(
        child: Text('Hello World'),
      ),
      theme: ThemeData(
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.blue,
        ),
      ),
    );
  }
}
```

This error is thrown when running `flutter run`. When I delete the import, there is no error

**Expected behavior**
No error

**device / execution context**
Running on iOS Emulator

**Comment by knaeckeKami** [comment]
Could you share your dependencies? This should not happen unless you use dependency overrides to gql_link 0.5.0

**Comment by vincenzopalazzo** [comment]
This happens if you clone a new project today I think, by the following rules `gql_link: ^0.4.2`

This is one of the reasons that I try to be reluctant to introduce breaking change often! We like to hack around and it is fine but a common user do this `gql_link: 0.4.2`.

There problem is gone, and also the user!

**Comment by leonvisscher** [comment]
@knaeckeKami 

My pubspec.yaml looks like this:

```
name: flutter_complete_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.0.0
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  flutter_signin_button: ^2.0.0
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

```
