### ISSUE TITLE
Upgrade web_socket_channel to ^3.0.1

### ISSUE THREAD

**Issue by Chralu** [zino-hofmann/graphql-flutter#1460]

**Comment by redDwarf03** [comment]
hello @Chralu, 
In the meantime, you can use this branch https://github.com/redDwarf03/graphql-flutter/tree/Web_socket_channel_301

Note that I've removed the examples for null safety reasons. I didn't see the point of updating in view of the new version that will be released.

**Comment by vincenzopalazzo** [comment]
>Note that I've removed the examples for null safety reasons. I didn't see the point of updating in view of the new version that will be released.

@redDwarf03 probably because your branch is not in sync with main, I see a lot of conflict inside the PR that you open

**Comment by redDwarf03** [comment]
> > Note that I've removed the examples for null safety reasons. I didn't see the point of updating in view of the new version that will be released.
> 
> @redDwarf03 probably because your branch is not in sync with main, I see a lot of conflict inside the PR that you open

I forked 5.1.2 and not 5.2.0 because 5.2.0 is a beta version not available in stable version

**Comment by vincenzopalazzo** [comment]
>I forked 5.1.2 and not 5.2.0 because 5.2.0 is a beta version not available in stable version

What is wrong with the "beta" version? in reality, you should use the 5.2 because the beta is just a staging version

**Comment by hagen00** [comment]
A number of packages now require web_socket_channel greater than version 3. `web_socket_channel` version 3.0.0 was released 5 months ago. 

Please update the beta version of graphql-flutter to make use of web_socket_channel 3.0.0 and up! Latest version of web_socket_channel is 3.0.1

**Comment by vincenzopalazzo** [comment]
>Please update the beta version of graphql-flutter to make use of web_socket_channel 3.0.0 and up! Latest version of web_socket_channel is 3.0.1

Currently not have enough time (outside of my free time) to work on this, if you can and want I will be available to review a PR for it.

**Comment by hagen00** [comment]
`graphql_flutter/pubspec.yaml` references `graphql: ^5.2.0-beta.8` in the dependencies. This will also have to change on merge. 

I have tested with my code base and everything seems to work normally. Unfortunately, `flutter test` doesn't work for me locally. Not sure if it should? Running on Ubuntu. 

I do not use graphql-flutter for subscriptions, so that is untested.

**Comment by vincenzopalazzo** [comment]
>I have tested with my code base and everything seems to work normally. Unfortunately, flutter test doesn't work for me locally. Not sure if it should? Running on Ubuntu.

not sure I usually ran `make check`.

>I do not use graphql-flutter for subscriptions, so that is untested.

Running the CI now, lets see what happens, if it will pass, we will merge it and if there is some problem we will revert the changes

**Comment by hagen00** [comment]
PR has been updated here: https://github.com/zino-hofmann/graphql-flutter/pull/1463

With some extra info.

**Comment by mingjunsiek** [comment]
Any update on this PR? Still waiting for this package to use web_socket_channel 3.0.0 and up

**Comment by hagen00** [comment]
Just made a change to the PR. Not sure if further changes to the versioning are required. Hopefully we can merge soon. I've been using my branch like below in production, but would obviously prefer to use the official package. 

```
graphql:
    git:
      url: https://github.com/hagen00/graphql-flutter.git
      ref: main
      path: packages/graphql
  graphql_flutter:
    git:
      url: https://github.com/hagen00/graphql-flutter.git
      ref: main
      path: packages/graphql_flutter
 ```

**Comment by redDwarf03** [comment]
@hagen00 any idea about the merge ? thx

**Comment by hagen00** [comment]
Unfortunately I don't know about merging it. @vincenzopalazzo will need to advise. I'm happy to do more work if needed. e.g to cleaning up code formatting etc...I'm also waiting to have it merged :( 

You can use my fork like this
```
graphql:
    git:
      url: https://github.com/hagen00/graphql-flutter.git
      ref: main
      path: packages/graphql
  graphql_flutter:
    git:
      url: https://github.com/hagen00/graphql-flutter.git
      ref: main
      path: packages/graphql_flutter
  ```
