### ISSUE TITLE
`Query` Widget, even if `operationName` is set -> "Must provide operation name if query contains multiple operations" 

### ISSUE THREAD

**Issue by D4G4** [zino-hofmann/graphql-flutter#884]
So I am providing a document with multiple operations, and thus am providing `operationName` in the `QueryOptions` like this:
```
var options = QueryOptions(
      document: gql(GAllQueries.allQueries()),
      operationName: GQueriesNames.kPaginatedComments,
      variables: variables,
      fetchPolicy: FetchPolicy.cacheAndNetwork,
    );
```
if I try to run the query directly using the client i.e. `client.query(options)` it works fine 
but if I do so using the `Query` widget, I get an error:

```
Query(
  options: options,
  builder: (
      QueryResult result, {
        Refetch? refetch,
        FetchMore? fetchMore,
      }) {
    return  _widget;
   }
  )
)
```

`QueryResult(source: QueryResultSource.network, data: null, context: Context({}), 
exception: **OperationException**(**linkException**: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: **Must provide operation name if query contains multiple operations., locations**: null, path: null, extensions: {code: INTERNAL_SERVER_ERROR, exception: {stacktrace: [GraphQLError: Must provide operation name if query contains multiple operations.,     at buildExecutionContext....`

using
`graphql_flutter: ^4.0.1`

**Comment by D4G4** [comment]
So in the `Query` widget class's code, the `QueryOptions` are converted into `WatchQueryOptions`, and `WatchQueryOptions` does not contain `operationName` field. 

Can this be the reason?

**Comment by ol88** [comment]
I believe this is related to my PR https://github.com/zino-app/graphql-flutter/pull/881

Currently closed but not merged because of null-safety moving to beta. Probably will need to re-open it but will wait an answer to this issue from maintainers first.

**Comment by ol88** [comment]
#881 has been merged to the beta branch but I don't think it's associated with any release yet.

@D4G4 you might want to test if that fixes your issue.

**Comment by kiloreux** [comment]
@ol88 This isn't currently included in any release. I can confirm with the latest beta release.

**Comment by ol88** [comment]
@kiloreux  It's in 5.0.0-beta.2
You might want to double check your pubspec.lock to make sure both graphql_flutter and graphql are using the 5.0.0-beta.2 release.

I actually had to force a fixed version in pubspec.yaml for it to work, just having `graphql_flutter: ^5.0.0-beta.2` kept graphql on the nullsafety branch as a transitive dependency. So I had to force my pubspec.yaml to look like this:
 ```
dependencies:
   graphql_flutter: 5.0.0-beta.2
   graphql: 5.0.0-beta.2
```

Then double check in pubspec.lock that you have:
```
  graphql:
    dependency: "direct main"
    description:
      name: graphql
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0-beta.2"
  graphql_flutter:
    dependency: "direct main"
    description:
      name: graphql_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0-beta.2"
```

Somehow I kept on having graphql: 5.0.0.nullsafety.5 as a transitive dependency otherwise. Not sure if that can help...
