### ISSUE TITLE
feat(subscription): implement new rising protocol `graphql-ws`

### ISSUE THREAD

**Issue by jjangga0214** [zino-hofmann/graphql-flutter#958]
[The official GraphQL specification](https://spec.graphql.org/) deliberately does not specify the transport layer.

For subscription, historically, [GraphQL over WebSocket Protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) by [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) library is widely adapted as de-facto standard.

However, the library is not actively maintained, and it officially recommends migrating to the "new" [GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) of [enisdenjo/graphql-ws](https://github.com/enisdenjo/graphql-ws).

Those two protocols are incompatible with each other.

The ecosystem is incrementally adapting to the new de-facto standard. 

Currently, `graphql_flutter` only implements `subscriptions-transport-ws`'s protocol. So, if a server uses `graphql-ws` protocol, `graphql_flutter` cannot be used.

Thus, hereby I request implementing a new protocol.

Thanks.

**Comment by sbatezat** [comment]
Thanks @jjangga0214 for these details. It should be mentionned on the readme that graphql-flutter is not supporting graphql-w protocol (and thus, it's - for now - a useless library as it's the new standard...)

**Comment by sarp86** [comment]
Would be nice to implemented as soon as possible. thx!

**Comment by maximilianmaihoefner** [comment]
I also needed this, so i put together a quick working example: https://github.com/maximilianmaihoefner/graphql-flutter/tree/graphql-transport-ws

You can try it out by specifying the following in your `pubspec.yaml`:
```
dependencies:
  graphql:
    git:
      url: https://github.com/maximilianmaihoefner/graphql-flutter/tree/graphql-transport-ws
      path: packages/graphql
      ref: graphql-transport-ws
  graphql_flutter:
    git:
      url: https://github.com/maximilianmaihoefner/graphql-flutter
      path: packages/graphql_flutter
      ref: graphql-transport-ws

dependency_overrides:
  graphql:
    git:
      url: https://github.com/maximilianmaihoefner/graphql-flutter
      path: packages/graphql
      ref: graphql-transport-ws
```

And specifying the new Subprotocol when creating the `WebsocketLink`:
```dart
final WebSocketLink websocketLink = WebSocketLink(
  subscriptionUri,
  config: const SocketClientConfig(autoReconnect: false),
  subProtocol: SocketSubProtocol.graphqlTransportWs,
);
```

The main changes have been made in (websocket_client.dart)[https://github.com/maximilianmaihoefner/graphql-flutter/blob/graphql-transport-ws/packages/graphql/lib/src/links/websocket_link/websocket_client.dart], it is however not a super clean implementation.
